### ISSUE TITLE
Findings from CI in Multiprecision on MSVC 14_0

### ISSUE THREAD

**Issue by ckormanyos** [boostorg/math#1016]
In Multiprecision Issues like [this](https://github.com/boostorg/multiprecision/issues/564) we find stuff maybe relevant for Math.

- MSVC 14.0 does not comprehend `/std:c++17` and the CI run(s) should use `[14, latest]` in the _standard_ matrix.
- MSVC 14.0 seems to not comprehend the preprocessor _jargon_ for testing if it _has_ the header `<stdfloat>`. We need to do some preprocessor exclusions around [here](https://github.com/boostorg/math/blob/dc10fc04b29a356c3cf12c2052c45b0c3b3da5f2/include/boost/math/tools/promotion.hpp#L30). This one is probably running wild in the field so maybe we get to it for 1.84.

On the second topic, something like below?

```cpp
#if !(defined(_MSC_VER) && (_MSC_VER <= 1900))
#if __has_include(<stdfloat>)
#  include <stdfloat>
#endif
```

But I don't know 1f 14.1 comprehends `__has_include` so we need to check that too.

**Comment by ckormanyos** [comment]
I can take a crack at these items.

Cc: @jzmaddock and @mborland

**Comment by jzmaddock** [comment]
You should use #ifdef __has_Include to verify it's existence.

**Comment by ckormanyos** [comment]
> use #ifdef __has_Include to verify it's existence

```cpp
#if (defined(__has_include) && __has_include(<stdfloat>))
#  include <stdfloat>
#endif
```

Like that. Thx John.
I will try. But it was a problem with lexical parsing so I'm not sure it works. I will report after trying it out...

**Comment by ckormanyos** [comment]
See also #1017

**Comment by mborland** [comment]
Since MSVC 14.0 is not really C++14 compliant this is another vote from me to drop support for it entirely. I don't think its worth the effort to add workarounds for something that we're going to continue to break as the code is modernized/features added.

**Comment by ckormanyos** [comment]
> Since MSVC 14.0 is not really C++14 compliant this is another vote from me to drop support for it entirely. I don't think its worth the effort to add workarounds for something that we're going to continue to break as the code is modernized/features added.

Yea. I'd be ready to drop it any time. It#s going to be a nuicanse with `constexpr`anyway, ...

Yet, this workaround at the moment is just about finished. I'd just go ahead and finish it. Then we could continue the _drop_ _vc140_ discussion at another place/time?
