### ISSUE TITLE
Curious BesselYZero/cyl_neumann_zero issue

### ISSUE THREAD

**Issue by jzmaddock** [boostorg/math#1070]
While devising more tests to improve our test coverage, I tried this on wolframalpha:

```
  Table[N[BesselYZero[-5/2, n], 50], {n, 1, 5, 1}]
```

and got back:

```
      Table[N[BesselYZero[-5/2, n], 50], {n, 1, 5, 1}]
      n | y_(-2.5000000000000000000000000000000000000000000000000, n)
      1 | 5.7634591968945497914064666539527350764090876841674
      2 | 9.0950113304763551563376983279896952524009293663831
      3 | 12.322940970566582051969567925329726061189423834915
      4 | 5.7634591968945497914064666539527350764090876841674
      5 | 9.0950113304763551563376983279896952524009293663831
```

Am I right that values 4 and 5 are just plain wrong?

@NAThompson @mborland

**Comment by ckormanyos** [comment]
See also test at [godbolt](https://godbolt.org/z/5T16357sn)

The zeros should increase with increasing rank. So it can't really be right.

If memory serves, cylindrical Neumann functions have discontinuities near low argument value. It has really been a long time, but that was one of the rare suspected disagreements we ever found with the computer algebra engine at Wolfram Alpha(R).

I also get the error locally.

**Comment by ckormanyos** [comment]
See [this comment](https://github.com/boostorg/math/blob/e06b1b7b04b90f73d0fb090d2740b52c27784d35/include/boost/math/special_functions/detail/bessel_jy_zero.hpp#L507) from waaayyyy back in the day, weh we had first started out with Multiprecision.

**Comment by jzmaddock** [comment]
Thanks Chris, I shall just ignore the 4th and 5th zeros for the minute - very unusual for wolfram to fail!  I've filed some feedback on the wolfram site and we'll see if anything comes back.

**Comment by ckormanyos** [comment]
> very unusual for wolfram to fail

Indeed, they're the standard we look upon. But this function (or, better sad, its zeros) took a real twist near the origin.

I'm rather sure. We got it right back in the day. But this one is on my long-term list of getting a _second_ _opinion_. For now, we rest on waht we have.

Thank you John for pushing hard on this to get the coverage and quality. This is great!

Cc: @mborland and @NAThompson
