### ISSUE TITLE
gauss_kronrod does not allow for non-literal types

### ISSUE THREAD

**Issue by SteveBronder** [boostorg/math#1077]
Using `gauss_kronrod` with a non-literal type causes a compiler error.

```
lib/boost_1.81.0/boost/math/quadrature/gauss_kronrod.hpp:139:41: error: the type ‘const std::array<stan::math::var_value<double>, 8>’ of ‘constexpr’ variable ‘data’ is not literal
  139 |       static constexpr std::array<T, 8> data = {
```

Example godbolt here

https://godbolt.org/z/K4Mxa85Mz

I think a fix would be to detect if the type is literal for the gauss kronrod detail and have one implimentation that uses static constexpr arrays and the other uses arrays constructed at run time

**Comment by SteveBronder** [comment]
It's a scalar autodiff type used in the stan math library. Looking at the definitions for [LiteralType](https://en.cppreference.com/w/cpp/named_req/LiteralType) it fails 

> a type with at least one constexpr (possibly template) constructor that is not a copy or move constructor,

I think for our purposes if `gauss_kronrod` allowed you to choose types for the weights/abscicca and a seperate type for the given functions return type then it would work for us and also fix the problem

**Comment by jzmaddock** [comment]
> Any ideas of how to support this?

Maybe, I think some experimentation might be needed though...

**Comment by SteveBronder** [comment]
> But the arena allocator . . . that seems more difficult to support

The arena allocator is at global scope so it's not an issue. 

I think just making a gauss kronrod detail that has something like `std::enable_if_t<is_literal<T>::value>` and another with the opposite would fix it

**Comment by jzmaddock** [comment]
> I think just making a gauss kronrod detail that has something like std::enable_if_t<is_literal<T>::value> and another with the opposite would fix it

That involves a huge amount of duplication: I have a simpler solution working here, but I need to see if I can reduce bloat even further...
