### ISSUE TITLE
boost::multiprecision::cpp_int leading zeros parsing bug

### ISSUE THREAD

**Issue by ohhmm** [boostorg/math#1119]
boost::multiprecision::cpp_int("000144") parsed into value 100.
See some details here: [https://github.com/ohhmm/openmind/blob/28b9ed5d55bf1766606442cc34689ee0c32671e7/omnn/math/test/Integer_test.cpp#L59](https://github.com/ohhmm/openmind/blob/28b9ed5d55bf1766606442cc34689ee0c32671e7/omnn/math/test/Integer_test.cpp#L59)

**Comment by mborland** [comment]
Duplicate from multiprecision

**Comment by ohhmm** [comment]
Hi. This doesn't look expected to me. But since it is C standard compliant, lets close this ticket.

**Comment by rhossack** [comment]
I ran into this issue trying to do project euler #55. If I try to create a cpp_int from a string that starts with a zero, it throws a wrapexcept.

**Comment by jzmaddock** [comment]
We will need a test case to investigate, but remember that all numbers starting with a 0 are parsed as OCTAL strings.  This is std lib compatible/compliant behaviour.
