### ISSUE TITLE
Skew normal distribution PPF incorrect for high skew

### ISSUE THREAD

**Issue by dschmitz89** [boostorg/math#1120]
This showed up in SciPy: https://github.com/scipy/scipy/issues/20124

Minimal Python reproducer:

```python

from scipy.stats import skewnorm
skewnorm.ppf(0.01, 500)  # 500 = skewness parameter

RuntimeWarning: Error in function boost::math::quantile(const skew_normal_distribution<d>&, %1%): Unable to locate solution in a reasonable time: either there is no answer to quantile or the answer is infinite.  Current best guess is %1%
-> 4.833181656374989e+142
``` 

SciPy recently updated to Boost's develop branch at [this commit](https://github.com/boostorg/math/tree/15c40fae1610fd83728d75e96d7377fe55f976f7), which did not solve this issue but only changed the error message to the one above.

Thanks in advance!

**Comment by jzmaddock** [comment]
Just looking at this now - that looks like a rather expensive way of computing derivatives, but more to the point, I have a hunch that for sufficiently high skewness you will always reach a point where the computation blows up: effectively the CDF becomes something like a square wave with zero derivative(s) either side of a near vertical crossover point.  I'm wondering if the TOMS748 algorithm might be a better choice here: it has robust root bracketing (provided you start the right side of zero).  It's a little worse than Newton in the smooth cases (typically ~ 12 iterations for double precision) but against that there's no need to compute roots?  I'm out today, but I'll try and experiment later...

**Comment by jzmaddock** [comment]
TOMS748 gets that particular case in 20 iterations which looks pretty good, but I need to devise some better tests and make sure it doesn't blow up anywhere...

**Comment by maresb** [comment]
Hey, sorry I missed out on this conversation. I have some thoughts regarding this. I'm fairly convinced that Newton's method would work great on the logit-CDF. Unfortunately, as far as I can tell, there is no numerically stable implementation of skewnorm CDF in the literature. (For positive skew and mildly-negative x, there is catastrophic cancellation when subtracting the Owen's T, even accounting for the `skew→1/skew` transformation.)

I think I know how to compute it stably, but I'm unfortunately slammed with other work at the moment.
