### ISSUE TITLE
Remove gcd tests from boost.math?

### ISSUE THREAD

**Issue by NAThompson** [boostorg/math#114]
It appears that the gcd is tested in boost.integer, but the tests are somewhat different. Does it make sense to remove the gcd unit tests from boost.math?

**Comment by jzmaddock** [comment]
Even though they're obsolete I retained them as I wanted to check backwards compatibility for anyone still using boost::math::gcd, but yes, now that the headers scream "deprecated" at you, I think we probably can remove them.

**Comment by NAThompson** [comment]
See #115
