### ISSUE TITLE
Code question: "argument reduction" in Cauchy `quantile_imp`

### ISSUE THREAD

**Issue by WarrenWeckesser** [boostorg/math#1171]
At this line

https://github.com/boostorg/math/blob/ab09ecec1d4cee65868951aa8dfe5ae4a1e4fa21/include/boost/math/distributions/cauchy.hpp#L147

`p` has already been validated, and the end points have been handled, so 0 < p < 1.  Is that line necessary?

This came up in a [scipy pull request](https://github.com/scipy/scipy/pull/21335).

**Comment by jzmaddock** [comment]
You're quite correct, not sure what was going on there :(

Will fix.
