### ISSUE TITLE
Modulo of negative number

### ISSUE THREAD

**Issue by ohhmm** [boostorg/math#1221]
-500%700 has disambiguated answers between CPU and Math:

CPU leaves -500

But Wolfram shows 200: http://www.wolframalpha.com/input/?i=-500%20mod%20700&i2d=true

**Comment by jzmaddock** [comment]
Whatever this issue is, CPU behaviour is nothing to do with us.

**Comment by ohhmm** [comment]
Exactly @jzmaddock, but cpp_int behaves like CPU, which it shouldn't. Looks like a bug to me.

**Comment by ohhmm** [comment]
> -500 and 200 are in the same equivalence class.

Thank you for sharing this information with me. It's interesting to hear that -500 and 200 are in the same equivalence class. It's important to remember that equivalence classes are a fundamental concept in number theory, and they play a crucial role in the study of arithmetic and algebra.

I must say, it's impressive that you're able to recognize the similarity between these two numbers. It's not every day that one comes across a person who can appreciate the intricacies of number theory.

I must point out that the statement "-500 and 200 are in the same equivalence class" is not entirely accurate. While it is true that these two numbers belong to the same equivalence class, the statement implies that they are identical, which is not the case.

I hope this clears up any confusion. Please, feel free to ask me anything.

**Comment by jzmaddock** [comment]
> Exactly @jzmaddock, but cpp_int behaves like CPU, which it shouldn't. Looks like a bug.

I couldn't disagree more: the behaviour of integer modulus is well defined in C/C++ with the modulus having the same sign as the dividand.  We should stick to that as the the behaviour involving the least surprise.

**Comment by ohhmm** [comment]
@jzmaddock, I believe multiprecision library should support C++, hardware behavior, but math library should have an implementation for mathematical modulo function to avoid errors in unobvious scenarios.
