### ISSUE TITLE
Boost.Math tests' poisoning of isnan can break standard libraries

### ISSUE THREAD

**Issue by BillyONeal** [boostorg/math#126]
https://github.com/boostorg/math/blob/develop/test/compile_test/poison.hpp defines a macro isnan. When I added an isnan assert into unordered_Xxx::max_load_factor, and that explodes. The standard explicitly prohibits doing this: http://eel.is/c++draft/requirements#macro.names

As a possible workaround, `poison.hpp` could include all standard library headers, not only math.h and cmath, if it wants to expose only its code to this.

(I have worked around this in MSVC++ for now but Boost shouldn't be doing this)

**Comment by jzmaddock** [comment]
The point is that some std lib's (and third party code) are still #defining isnan/isinf etc and this causes our code to explode unless we always make calls to those functions in such a way that macro expansion is disabled.  It's a similar situation to the min/max macros in msvc.  So... the point of this header is simply to validate that we're calling those functions "correctly".

So... I guess my question is how come you're #including our private testing headers?

**Comment by pabristow** [comment]
I’m sure John Maddock will provide a more expert reply, but as I understand it the whole idea of using this header and running the test is to make sure it *doesn’t* compile (and is only used when running Boost.Math *tests* rather than in normal use).

But is *your* problem that it doesn’t only cause an engine-stall compile fail, but blows a head gasket – crashing the compiler?

Paul

**Comment by BillyONeal** [comment]
> The point is that some std lib's (and third party code) are still #defining isnan/isinf etc and this causes our code to explode

I get that, but <unordered_map> and <unordered_set> (and other standard library headers) are under no obligation to support a broken C99 implementation when they ship with a working C99 implementation.

> I guess my question is how come you're #including our private testing headers?

We are running your tests with nightly builds of the compiler and standard library to make sure we don't break you. I added an assert to unordered_Xxx::max_load_factor, e.g. _STL_ASSERT(!_STD isnan(_New_load_factor)). But because your tests are exposing standard library headers to this that doesn't compile. I have worked around it in <unordered_foo> for now but we are concerned about expanding the min/max/NOMINMAX mess to even more names.

> But is *your* problem that it doesn’t only cause an engine-stall compile fail, but blows a head gasket – crashing the compiler?

Given that the standard explicitly makes this UB it isn't the standard library's problem, no. Even if it did make the compiler "blow a head gasket" that wouldn't technically be the compiler's problem either but ICEs are always bugs :)

**Comment by NAThompson** [comment]
> The point is that some std lib's (and third party code) are still #defining isnan/isinf etc and this causes our code to explode

Maybe we should file some bug reports against the implementations that do this. It sounds like something that would've been useful in `C++03`, but can now be safely avoided with the keyword pandemonium of `inline const constexpr . . .`. But is there any chance we will win?

**Comment by jzmaddock** [comment]
>Maybe we should file some bug reports against the implementations that do this. It sounds like something that would've been useful in C++03, but can now be safely avoided with the keyword pandemonium of inline const constexpr . . .. But is there any chance we will win?

As this mostly effects "legacy" platforms it's unlikely.

>We are running your tests with nightly builds of the compiler and standard library to make sure we don't break you.

Ah OK, got it, and yes you are correct that this could randomly break new std lib releases - I'll have to do as you suggest and #include all the std lib headers we use before poisoning those macros.  I'm actually a bit surprised that those headers are pulled in at all as we don't explicitly include them.

BTW it's worth pointing out that the one test that uses this (std_real_concept_check) breaks the letter of the std anyway as it declares classes and functions in namespace std.  It does catch bugs that are otherwise almost impossible to track down though...

**Comment by BillyONeal** [comment]
> I'm actually a bit surprised that those headers are pulled in at all as we don't explicitly include them.

If you pull in different headers you're likely to get these bits. For example, `<functional>` needs `<unordered_map>` to implement C++17 boyer_moore search.

>BTW it's worth pointing out that the one test that uses this (std_real_concept_check) breaks the letter of the std anyway as it declares classes and functions in namespace std. 

Yeah, if you are getting away with it, I'm not saying we need to go out of our way to make problems for ya :).  I cite the standard here mostly as a justification of "even though my change to <unordered_map> is most recent, the change is justified." After all, the whole reason you have this mess at all is to workaround implementations that aren't meeting their end of the contract :)

**Comment by NAThompson** [comment]
Should we close this issue? It looks like John has a reasonable solution if it works for Billy.

**Comment by jzmaddock** [comment]
No further updates so closing down.
