### ISSUE TITLE
`formula_format` only defined in .cpp file

### ISSUE THREAD

**Issue by NAThompson** [boostorg/math#157]
In the [polynomial documentation](https://www.boost.org/doc/libs/release/libs/math/doc/html/math_toolkit/polynomials.html), a very nice function called `formula_format` is discussed. However, grepping through the project, the only place I can find the definition of this function is in `example/polynomial_arithmetic.cpp`, and hence I can't `#include` it anywhere in my own code.

This `formula_format` should be made a member function on the `polynomial` class, or a free function somewhere accessible.

**Comment by ilazaric** [comment]
The implementation of `formula_format` in `example/polynomial_arithmetic.cpp` does not work with
`polynomial<std::complex<double>>` (it uses comparison). Also, it probably should not return a `string`, but a wrapper `polynomial_pretty<T>`, so it can access the stream manipulators.

**Comment by jzmaddock** [comment]
Just catching up on these old issues.... :)

I can't help wondering if what we really need is a proper pretty-formatting library for numerical data.  Complete with multiple output formats (text, html, Tex, Docbook etc), plus multiple input formats (number, complex, interval, polynomial, array etc) each of which builds simpler constructs below it.

It's not something I want to take on right now, but I do sort of like the idea (and it would be pretty darn useful).

**Comment by NAThompson** [comment]
@jzmaddock : I think you're onto something here; that'd be a huge improvement. For now, I'm personally unable to contribute to that effort, and in addition, it might be good to backburner it until the C++ committee decides on what the right way to do unicode is. Then we could use subscripts/superscripts and so on.
