### ISSUE TITLE
unusual characters in lambert_w.hpp

### ISSUE THREAD

**Issue by imc-123** [boostorg/math#192]
Compiling boost-math fails under MSVC when using the /utf-8 command-line option. (This tells it to assume the source files are utf8 encoded.)
The error occurs on line 1865 of lambert_w.hpp which contains code page 1252 smart quotes (0x93, 0x94) and an en-dash (0x96) -
`// On the Lambert W function,  Adv.Comput.Math., vol. 5, pp. 329359, 1996.`

These 3 bytes, being followed by values in the range 0x00-0x7F, are invalid in utf8 encoding and hence the compiler complains.

Are boost source files specified to use Windows 1252 code page, or should compiling assuming utf-8 work ?

**Comment by NAThompson** [comment]
Fixed in 166e5fb5130ac76d38c4056236e7f408b009702e

**Comment by jzmaddock** [comment]
Thanks Nick!

**Comment by NAThompson** [comment]
No problem; should this be cherry picked into the release? It's strange that no one else hit it before.
