### ISSUE TITLE
Add nvcc to test matrix

### ISSUE THREAD

**Issue by NAThompson** [boostorg/math#194]
The goal here is to make sure that no host code is broken when using nvcc; clearly at this point we have no device code. (Actually, is this an feature request for boost.config?)

**Comment by jzmaddock** [comment]
Probably for config first yes.

This is harder than it looks too as neither appveyor, nor travis have nvcc installed, and neither can run device code.
Also be aware that compiling a .cpp file with nvcc is sort of pointless as it just forwards to the host compiler, it's only when you build a .cu file that the nvcc compiler itself does any work.
