### ISSUE TITLE
Math.Quaternion private members

### ISSUE THREAD

**Issue by CaeruleusAqua** [boostorg/math#221]
Is it really necessary that the members of Quaternion are private?
This will break all libraries that inherit from math.quaternion!
Just switching from private to protected solves the problem for me (with testet math).

This was changed in commit 68b82322ab2ea972f14122ea7a039011d12f1723.

**Comment by jzmaddock** [comment]
I think I'm closing this as "won't fix" as inheritance results in the operators slicing the class.  The public interfaces should really provide what you need in any case?
