### ISSUE TITLE
Deprecated header and underflow warnings

### ISSUE THREAD

**Issue by NAThompson** [boostorg/math#237]
```
In file included from test_1F0.hpp:13:0,

                 from test_1F0.cpp:6:

../../../boost/test/floating_point_comparison.hpp:14:152: note: #pragma message: This header is deprecated. Use This header is deprecated. Please use <boost/test/tools/floating_point_comparison.hpp> instead. instead.
```

I'll just fix this whenever I get the chance; low priority.

Also, thousands of lines of:

```
hypergeometric_1f1_large_regularized.ipp:1150:7: warning: floating constant truncated to zero [-Woverflow]

       { SC_(2.2103403323709479866940105602712347713881e-31), SC_(1.2220855000000000000000000000000000000000e+06), SC_(1.0184045000000000000000000000000000000000e+06), SC_(1.1011379385218373966166313545729000750778e-6908211) }, 
```

in [this](https://travis-ci.org/boostorg/math/jobs/569821331) log. Actually, I don't know what to do about that. It's clearly harmless, and it does clearly underflow, so in a sense the pain is only generated by the compiler  . . .

**Comment by NAThompson** [comment]
I'm working on a fix for the header deprecations; should be straightforward.

**Comment by NAThompson** [comment]
I think I see the problem for the literal range:

```
lang-darwin.compile.c++ ../../../bin.v2/libs/math/test/test_1F1_float.test/clang-darwin-10.0/debug/link-static/threading-multi/visibility-hidden/test_1F1.o
warning: unknown warning option '-Wno-literal_range'; did you mean '-Wno-literal-range'? [-Wunknown-warning-option]
````

**Comment by NAThompson** [comment]
Fixed in [https://github.com/boostorg/math/commit/0445f5c2cc20f5be2e15fb8b22bc0d0e85844c53](0445f5c).

**Comment by evanmiller** [comment]
The underflow warnings still appear with GCC, e.g. here:

https://travis-ci.org/github/boostorg/math/jobs/746061269

They are now tripped by the `-Woverflow` flag. I have a ham-fisted fix [here](https://github.com/evanmiller/math/commit/30fadae9781a442253c988a595ffab30a2538732) which simply replaces the offending literals with zeroes. Happy to open a pull request with it, but I didn't want to contribute needlessly to the Travis CI Holiday Traffic Jam.

**Comment by jzmaddock** [comment]
Yeah, the Travis traffic jam is a problem :(   I think your fix is fine, as long as only values that will underflow even in any conceivable long double are replaced.  I still think that GCC is being over picky though!

**Comment by evanmiller** [comment]
@jzmaddock I used a cut-off of 1e-10000, which is roughly the square of the smallest representable quad-precision number (~1e-4932).

Would you be interested in switching the project from Travis to GitHub Actions? In my experiments, the build time for 56 jobs is less than an hour on GitHub (compared to 12+ hours for 67 jobs with Travis).
