### ISSUE TITLE
lgamma without `double` to `long double` propagation easily overflows

### ISSUE THREAD

**Issue by wds15** [boostorg/math#242]
When disabling the `double` to `long double` propagation of the `boost::math::lgamma` then the function is a lot faster (comparable to `std::lgamma`)... but the boost version now overflows easily for large arguments at around 1E25 (still ok) while 1E27 leads to NaN. The `std::lgamma` implementation returns results up to 1E300 which is close to the maximal `double` representable. In fact, the `boost::math::lgamma` implementation is also able to return results for these large arguments, but only if the `double` to `long double` propagation is used.

Quickly inspecting the code of `lgamma` shows that most of the computation is done on the natural scale instead of the log scale which seems to be the source of the problem.

I would expect the boost `lgamma` to return correct results for the same support as `std::lgamma` even if `double` to `long double` propagation is turned on.

**Comment by jzmaddock** [comment]
This should definitely work - we do try really hard not to get spurious over/underflow - I'll look into it shortly.

**Comment by wds15** [comment]
Thanks!

**Comment by jzmaddock** [comment]
Well ironically.... this turns out to be an optimisation issue, if you comment out:

```
#include <boost/math/special_functions/detail/lanczos_sse2.hpp>
```

In lanczos.hpp then everything is fine.

Unfortunately the x64/SSE2 optimised code fails when z > sqrt(DOUBLE_MAX), I need to rethink that.

**Comment by jzmaddock** [comment]
Please see commit above for the fix.
