### ISSUE TITLE
Update release notes

### ISSUE THREAD

**Issue by jzmaddock** [boostorg/math#264]
What do we need in the release notes for 1.72?

**Comment by NAThompson** [comment]
- Cardinal B-splines as continuous functions
- Cardinal quintic B-spline interpolation which allows stable evaluation of second derivatives of interpolated data
- Cardinal trigonometric interpolation
- Deprecation of `boost/math/tools/univariate_statistics.hpp` and `boost/math/tools/bivariate_statistics.hpp`, in favor of `boost/math/statistics/univariate_statistics.hpp` and `boost/math/statistics/bivariate_statistics.hpp`.
- One-sample Student's t-test
- Anderson-Darling test for normality
- Ljung-Box test for autocorrelation
- Runs test for a distribution-free test of randomness

**Comment by NAThompson** [comment]
What is the release schedule? Should we do a merge to master and freeze right now?

I was hoping to get ordinary least squares regression and median absolute deviation linear regression in before the release. . .

**Comment by jzmaddock** [comment]
We have a week before major changes should be frozen, and 2 before a complete freeze: https://www.boost.org/development/index.html

**Comment by NAThompson** [comment]
Ok, let's merge to develop now to make sure we don't have any problems and we'll see if there's time to get the linear regression in contingent on the result of that. You have anything you still want in?

**Comment by jzmaddock** [comment]
I've updated our notes and merged to master.

There may or may not be other merges before 1.72....
