### ISSUE TITLE
Boost includes <mpreal.h> that it doesn't install and isn't available in the system

### ISSUE THREAD

**Issue by yurivict** [boostorg/math#273]
The FreeBSD package boost-libs-1.71.0_1 installs the file ```/usr/local/include/boost/math/bindings/mpreal.hpp``` that contains:
```
#include <mpreal.h>
```
that is not installed by boost and isn't available in the base system or through its dependencies.

**Comment by jzmaddock** [comment]
Right, the header is there as a bit of "glue" to allow the extended precision library mpreal to interoperate with Boost.Math.  Nothing in Boost.Math will include this header,  and if you're not using mpreal then you won't ever include it in user code either.
