### ISSUE TITLE
test_long_double_support.cpp failed in sinh part in clang on Windows

### ISSUE THREAD

**Issue by yuxianch** [boostorg/math#274]
I was using clang-cl on Windows to run the tests from math module, and found [test_long_double_support.cpp](https://github.com/boostorg/math/blob/develop/test/test_long_double_support.cpp) failed in sinh part.
This is what I got when executing this test.
```
...
std::sinh<long double> Max = 0 RMS Mean=0

std::asinh<long double> Max = 0 RMS Mean=0

::sinhl<long double> Max = 0 RMS Mean=0

unknown location(0): fatal error: in "test_main": memory access violation occurred at address 0x00000001, while attempting to  read inaccessible data
test_long_double_support.cpp(348): last checkpoint: "test_main" test entry

*** 1 failure is detected in the test module "Master Test Suite"

EXIT STATUS: 201
```
In the same time, cl can successfully run this test. 
Could someone explain the reason?
If you need more information, please let me know.

**Comment by jzmaddock** [comment]
That test doesn't include any of Boost.Math:  it's there to verify that the C++ std lib is functional for type `long double`.  If you can work out which call is responsible, you should be able to reproduce without any of Boost.

**Comment by jzmaddock** [comment]
I tried to reproduce with:

clang-cl /GS /W3  /Gd /MDd /EHsc -DBOOST_ALL_NO_LIB -I../../.. -I../include_private test_long_double*.cpp <other sources>

and it built and ran just fine.

**Comment by jzmaddock** [comment]
Oops, that command line was supposed to indicate that there were other source files after the one given :(
