### ISSUE TITLE
Prolate spheroidal wave function

### ISSUE THREAD

**Issue by NAThompson** [boostorg/math#277]
A perhaps nice addition to the suite of special functions might be the [prolate spheroidal wave functions](https://www.ntu.edu.sg/home/lilian/Review-PSWFs-final.pdf). These functions are the set of bandlimited functions whose norm is maximally concentrated in a finite time interval, and hence are useful for modeling attenuated signals.

**Comment by pabristow** [comment]
Looks interesting ;-)

I note that 

Algorithm 840: Computation of Grid Points,
Quadrature Weights and Derivatives for Spectral Element Methods Using Prolate Spheroidal Wave Functions—Prolate Elements
JOHN P. BOYD

uses Matlab and 'eigen-stoff' but probably Boost.uBlas or Eigen would suffice?

I've put it in my Possible TODO file :-)

**Comment by NAThompson** [comment]
Closed as moved to wishlist.
