### ISSUE TITLE
Quadrature test fail after correcting typos

### ISSUE THREAD

**Issue by pabristow** [boostorg/math#281]
https://github.com/boostorg/math/commit/9029e747b4cca33c4ba81eec8a4bbbdee4ffb49c
shows the changes made correcting typos found by Brian Wignall's program.

I've searched for all mentions of quadrature in *.*pp files

include/boost/math/quadrature/trapezoidal.hpp

include/boost/math/quadrature/detail/tanh_sinh_detail.hpp

have changes but they are only in comment or strings, so I don't see this as the cause.

https://www.dropbox.com/s/czul53tibz3s4fx/.math_test_18dec2019.log?dl=0

is the full test log

I:\boost\libs\math\test>b2 -a > .math_test_18dec2019.log is command line

MSVC 14.2, default C++ std = c++14 I think (but not sure).

I suspect this test is running but it should not because requires something that isn't present.

GCC libquadmath and __float128 support : no

When (if) the testers get round to it, cause may become clearer?

**Comment by ckormanyos** [comment]
line 46 of:
* boost/math/quadrature/trapezoidal.hpp
appears as if it has received an actual change in source code.
I can not see a problem with the change. But maybe look there?
... For a hidden character or something unusual?

**Comment by ckormanyos** [comment]
Paul,
There are also more tangible errors listed in the log you posted in drop box.

We find numerous messages such as:
```
I:\boost\boost/memory_order.hpp(57): error C2144: syntax error: 'boost::memory_order' should be preceded by ';'
I:\boost\boost/memory_order.hpp(57): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
```

I don't know exactly what version of Boost you are using to test. So I am unable to investigate the compiler switches that MSVC is detecting issues with.

Kind regards, Chris

**Comment by pabristow** [comment]
The changes in include/boost/math/quadrature/trapezoidal.hpp are only in the error message string as far as I can see.

I've just used develop branch to test - but foolishly I didn't test before making the change. Perhaps I should go back to pre-typo removal/

**Comment by pabristow** [comment]
I have wound back to 8c9fc93094003a8fbc396da90fb5f8ecf7560e50 before the typo changes with the same result. So the typos are very probably NOT the cause.

I suspect this is more likely an up-coming problem with the atomic library using the latest MSVC Preview compiler.  The regression tester do not yet use this version.
