### ISSUE TITLE
Typo in cardinal cubic spline header guard

### ISSUE THREAD

**Issue by MarcusKlik** [boostorg/math#287]
Hi, thanks for providing a fantastic library.

There is a small typo in the _cubic spline header guard_ which throws a warning with some compilers. An example warning can be seen in [this build](https://travis-ci.org/fstpackage/synthetic/jobs/627782991#L1564) (line 1564).

thanx!

**Comment by NAThompson** [comment]
Actually, that is not just a warning, that typo could contort itself into a large number of significant errors. Thanks so much!

**Comment by MarcusKlik** [comment]
thanks, you're very welcome!
