### ISSUE TITLE
meaning of confidence intervals

### ISSUE THREAD

**Issue by schneeregenflocke** [boostorg/math#295]
https://github.com/boostorg/math/blob/a422b02a2d4383264f6cc0cb2cee0bc0d708f557/doc/distributions/students_t_examples.qbk#L6-L12

<a href="https://ibb.co/ih7BWU"><img src="https://preview.ibb.co/cRmid9/Papula-Seite-524-Beispiel.png" alt="Papula-Seite-524-Beispiel" border="0"></a>

Isn't the reasoning too imprecise? The meaning differs for other or more reasons?

If the variances were estimated using the samples in the figure above and the confidence intervals were calculated using the t-distribution, the lengths of the confidence intervals would be different and would no longer correspond _individually_ to the probability of 95%, as in the figure above, of containing the true mean.

**Comment by NAThompson** [comment]
I'll have to punt this one to either @jzmaddock  or @pabristow . I've been intending to think more deeply about confidence intervals but haven't found the time.

**Comment by schneeregenflocke** [comment]
I was irritated by the sentence ... 

> note that the interval either contains the true mean or it does not

A mind game: Someone rolls the die without knowing the result, he covers the die after throwing. Is there or was there a probability now to roll a certain number?

kind regards, Marco
