### ISSUE TITLE
Method to compute nth roots of unity 

### ISSUE THREAD

**Issue by anshu-khare-design** [boostorg/math#308]
Nth roots of unity is very significantly used in geometry.
They are used to generate vertices of a regular polygon. 
They are also used in number theory, the theory of group characters, and the discrete Fourier transform.

This is a proposal to generate a method to compute nth roots of unity wheather real or imaginary.

**Comment by NAThompson** [comment]
Wut? That's just

```
std::complex<double> arg{0, 2*M_PI*n/N};
std::exp(arg);
```

**Comment by anshu-khare-design** [comment]
I am interested in generating an output as follows:

If a user types roots_of_unity(4).

It should give an output as
(1,0), (0,1), (-1,0), (0,-1) as they are in the complex plane.
Later using image library we can generate the polygon with the marked points in the conmplex plane.

**Comment by NAThompson** [comment]
Generating textual output is really not what this library does, nor does it really provide primitives as trivial as the roots of unity.
