### ISSUE TITLE
Dirichlet Distribution

### ISSUE THREAD

**Issue by mrityunjay-tripathi** [boostorg/math#317]
There is no [Dirichlet distribution](https://en.wikipedia.org/wiki/Dirichlet_distribution) in either armadillo or boost. Can we implement it in boost?
Reference: https://mast.queensu.ca/~communications/Papers/msc-jiayu-lin.pdf

**Comment by NAThompson** [comment]
I just looked at your links; seems useful and straightforward to implement numerically. Unfortunately, I personally am backlogged with wavelets and multivariate interpolation, so you'll either have to submit a PR or convince @pabristow or @jzmaddock that it's cool enough for them to do it.

**Comment by mrityunjay-tripathi** [comment]
> so you'll either have to submit a PR or convince @pabristow or @jzmaddock that it's cool enough for them to do it.

No worries. I can work on it.
> As to consolidation, could you add it to the feature wishlist?

Sure. :)

**Comment by pabristow** [comment]
Much of the work in adding a distribution is in devising a suite of tests to confirm correctness and precision/accuracy, and writing documentation, and an example of use.  A working implementation gives a head start.  If you can help with these, then I might be persuaded to tackle it.

**Comment by mrityunjay-tripathi** [comment]
@pabristow Sure. I am currently getting familiar with the codebase.

**Comment by NAThompson** [comment]
Just to keep things tidy, I'm going to close this and let the feature wishlist be the point of authority for this issue.
