### ISSUE TITLE
math/statistics/non-central chi square documentation

### ISSUE THREAD

**Issue by nbecker** [boostorg/math#344]
The description of the pdf in
https://www.boost.org/doc/libs/1_72_0/libs/math/doc/html/math_toolkit/dist_ref/dists/nc_chi_squared_dist.html

mixes 2 symbols, k and v.  There should only be one of them: k and v are the same (the degrees of freedom).  c.f., https://en.wikipedia.org/wiki/Noncentral_chi-squared_distribution

**Comment by ambreshbiradar9** [comment]
Hi @nbecker,
can I convert k to v?
I am new to git and opensource

**Comment by NAThompson** [comment]
@ambreshbiradar9 : Yes, try [this file](https://github.com/boostorg/math/blob/develop/doc/distributions/nc_chi_squared.qbk).

**Comment by ambreshbiradar9** [comment]
> @ambreshbiradar9 : Yes, try [this file](https://github.com/boostorg/math/blob/develop/doc/distributions/nc_chi_squared.qbk).

please forgive me I very new to this

I did not understand how to use the above link 

actually i have clonned the repo and i am modifying the above mentioned html file.

**Comment by jzmaddock** [comment]
Sorry we weren't clearer - we need to fix the docs - but basically k and v are just different names for the degree of freedom parameter, and whichever we use we meant the same thing.

**Comment by ambreshbiradar9** [comment]
@NAThompson 

please forgive me I am new to this 
I did not understand how to work on your given file link

I am changing k to v
can i change the html file from the path :
libs/math/doc/html/math_toolkit/dist_ref/dists/nc_chi_squared_dist.html
and also corresponding equation files as well like from
boost/libs/math/doc/equations/nc_chi_squ_ref1.svg

**Comment by NAThompson** [comment]
The html file is generated from the `.qbk`. For the svg, you'll need to regenerate it using this: https://viereck.ch/latex-to-svg/

**Comment by NAThompson** [comment]
@ambreshbiradar9 : Fork this repo, create a draft PR, and I'll help you out.

**Comment by NAThompson** [comment]
Fixed in #367
