### ISSUE TITLE
No isnan for real_concept

### ISSUE THREAD

**Issue by NAThompson** [boostorg/math#352]
It looks like `isnan` slipped through the cracks on `real_concept`:

```
test/math_unit_test.hpp:79:14: error: no matching function for call to 'isnan(boost::math::concepts::real_concept&)'
   79 |     if (isnan(computed))
      |         ~~~~~^~~~~~~~~~
```

**Comment by NAThompson** [comment]
Fix coming for `isnan`, but also we have this problem, which seems harder:

```
test/math_unit_test.hpp:94:39: error: invalid static_cast from type 'boost::math::concepts::real_concept' to type 'int64_t' {aka 'long long int'}
   94 |         detail::total_ulp_distance += static_cast<int64_t>(dist);
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by jzmaddock** [comment]
It was deliberate - we assumed C++03 support only.  The call to isnan should be protected against macro expansion as well - there are sadly still systems out there that #define that.

Does:

```
using boost::math::isnan;
using std::isnan;
```

Fix things?

Likewise the lack of a (lossy) cast to integer is deliberate.

Use either boost::math::itrunc, ltrunc or lltrunc.

**Comment by NAThompson** [comment]
Ok, so adding `max` and `isnan` to `real_concept` is not desired? Or is it reasonable given that `real_concept` is only for internal use?

**Comment by jzmaddock** [comment]
>Or is it reasonable given that real_concept is only for internal use?

It's purpose is to model the "minimum conceptual requirement" for a number type, adding stuff changes what that requirement is.  So no, not such a good idea I'm afraid!

**Comment by NAThompson** [comment]
@jzmaddock : Ok, cool; I'll get rid of those diffs in the feigenbaum PR.
