### ISSUE TITLE
boost::math::pow is not constexpr

### ISSUE THREAD

**Issue by pabristow** [boostorg/math#354]
`constexpr  int i = boost::math::pow<8>(2);`

MSVC 2019 c++std=17 reports

error C2131: expression did not evaluate to a constant

 ` const  int i = boost::math::pow<8>(2);` //  gives the expected 256.

Is there any reason why this could not be constexpr?

**Comment by NAThompson** [comment]
Sorry I'm gonna have to punt on this one; I have no clue what the `constexpr` rules are . . .

**Comment by cosurgi** [comment]
Would be cool if pow was constexpr.
