### ISSUE TITLE
error: ‘is_same_v’ is not a member of ‘std’

### ISSUE THREAD

**Issue by rilesdg3** [boostorg/math#355]
In univariate_statistics.hpp line 32 **else if constexpr (std::is_same_v<typename** 

is using **std::is_same_v** which is not a part of std:: in c++11, and c++14. The readme file says requires at least c++11, I think you might want std::is_same or std::experimental::is_same_v if the file is to work in c++11, and c++14?

If you use std::experimental::is_same_v you will have to

#include <experimental/type_traits>

**Comment by ckormanyos** [comment]
> If you use std::experimental::is_same_v you will have to

Correct.

`is_same_v` came in C++17, as did several other helper templates in `<type_traits>`.

I wonder if Boost has a compiler conditional that does the same?

**Comment by jzmaddock** [comment]
That file requires C++17 anyway - note the `else if constexpr`.

@NAThompson is the requirement documented?

We should probably add some PP logic with a #error when `BOOST_NO_CXX17_IF_CONSTEXPR` is defined, or when `__cpp_lib_type_trait_variable_templates ` is not defined?

**Comment by NAThompson** [comment]
It's definitely intentional, without `if constexpr` the functions don't work on integer types.

I'll document this, and also change the namespacing to `namespace boost::math::statistics` so that we have a giant flag that this requires C++17.

**Comment by rilesdg3** [comment]
I changed it to std::experemental::is_same_v and I am able to compile and run it with -std=c++14. I don't how it works in c++14 because of the if constexpr is c++17 but it does

**Comment by jzmaddock** [comment]
>and also change the namespacing to namespace boost::math::statistics so that we have a giant flag that this requires C++17.

@NAThompson that would be a breaking change:  is the namespace change really required?

**Comment by NAThompson** [comment]
@jzmaddock : It is not required; however, it is one of the simplest C++17 features, and so there aren't, so my knowledge, and C++17 compilers that don't support it.

**Comment by NAThompson** [comment]
Fixed in develop.
