### ISSUE TITLE
[Not an Issue] Fast nth fibonacci numbers

### ISSUE THREAD

**Issue by madhur4127** [boostorg/math#371]
A while back, I wrote a routine for [fast nth fibonacci number](https://github.com/CodeISM/ccptl/blob/master/Number%20Theory/fibonacci.h) calculation.

Is boost/math interested in adding this to the library?

I could add the functionality if the library's interested.

**Comment by NAThompson** [comment]
Should it go in boost.integer?

**Comment by madhur4127** [comment]
> Should it go in boost.integer?

The code that is linked only works it for *standard* C++ integers but I think it can be extended to work with arbitrary precision.

**Comment by NAThompson** [comment]
I personally think it's a cool addition.

The Fibonacci numbers grow so fast it might be nice to allow for arbitrary sized integers.

**Comment by madhur4127** [comment]
> Also, is there a fast way to detect if it's going to overflow? It might be nice to (say) return -1 if we know it'll overflow.

Binet formula can be used for a rough approximation, so the problem will reduce to whether the given number fits in the limit.

But this will be a problem if someone tries to use a modular integer wrapper (considering that it takes the "integer" type as a template parameter) and only needs the modulus of the Fibonacci number. In this case, it will never overflow.

**Comment by NAThompson** [comment]
Can you do compile-time detection of where it's a modular type?

**Comment by madhur4127** [comment]
> Can you do compile-time detection of whether it's a modular type?

I am out of ideas for that :(

**Comment by jzmaddock** [comment]
>Can you do compile-time detection of whether it's a modular type?

That's tough: we don't have modular type yet in multiprecision, so we don't have our own trait, and numeric_limits doesn't really give us the option of distinguishing between fixed precision integers that handle overflow as 2^n modular arithmetic, and "deliberately" modular types that are modulo some number that perhaps isn't a 2^n.

**Comment by NAThompson** [comment]
Ok, cool. Just to clarify, I think it's a cool idea whether or not we can take care of this inconvenience without heroics.
