### ISSUE TITLE
Bug in ibeta_power_terms

### ISSUE THREAD

**Issue by evanmiller** [boostorg/math#372]
Thank you for an excellent library. I don't have a test case for this, but the following line of code is not correct:

https://github.com/boostorg/math/blob/3cc1ebef5e5ece525770692907e7d10df84ec5a4/include/boost/math/special_functions/beta.hpp#L517

I.e. it both adds and subtracts `lgamma(c)`. I believe the line should instead read:

```
 log_result += boost::math::lgamma(c, pol) - boost::math::lgamma(a) - boost::math::lgamma(b, pol);
```

It is somewhat concerning that the commit that added this code https://github.com/boostorg/math/commit/238436ee0781593e6c38fe240b390a251bad72e3 also loosened the test tolerances in several places. However, I have not run the tests with the proposed modification to see if the fix brings the code back in line with the old tolerances.

**Comment by NAThompson** [comment]
Thanks for the heads up!

What (rough) values of the arguments did you see this? I just made an ULPs plot and couldn't see anything (although of course this will be tautological if both the `long double` and `float` implementation are wrong.)

```cpp
#include <iostream>
#include <string>
#include <boost/math/tools/ulps_plot.hpp>
#include <boost/math/special_functions/beta.hpp>

int main() {
    auto f = [](long double x) {
        return boost::math::beta(x, 2);
    };

    auto g = [](float x) {
        return boost::math::beta(x, float(2));
    };

    using boost::math::tools::ulps_plot;

    std::string filename = "beta_bug.svg";
    int samples = 10000;
    int width = 700;
    long double clip = 2.5;
    auto plot = ulps_plot<decltype(f), long double, float>(f, float(2), float(10), samples);

    plot.clip(clip).width(width);
    plot.add_fn(g);
    plot.write(filename);
}
```

<img width="692" alt="Screen Shot 2020-06-17 at 8 59 04 PM" src="https://user-images.githubusercontent.com/5459618/84965631-63fce300-b0dd-11ea-960c-8cb62ad6ea27.png">

**Comment by evanmiller** [comment]
Thank you for the prompt reply. I just came across the line in question while trying to understand the code - it's possible that the pathway is not hit at all.

**Comment by evanmiller** [comment]
Note that the triggering condition is `!isnormal(result)` rather than `!isnormal(x)`.

**Comment by jzmaddock** [comment]
Good spot!  It's clearly my mistake - the final `- boost::math::lgamma(c, pol)` should be `- boost::math::lgamma(b, pol)`.  Which is to say we are dividing (by logs) by `beta(a, b)`.

@NAThompson : this won't show up with type double or float - this code only kicks in for types with no available Lanczos approximation (ie multiprecision types).

I'm testing now to see if we have coverage of this, or if it's a bit of defensive programming against spurious overflow...

**Comment by jzmaddock** [comment]
PR fix pushed, thanks for the nudge!

**Comment by jzmaddock** [comment]
I think this should now be addressed in develop.

**Comment by evanmiller** [comment]
@jzmaddock Nope:

https://github.com/boostorg/math/blob/fa23c83bb1b46a2a21a98f667f01db0f18b6e486/include/boost/math/special_functions/beta.hpp#L517

It's fixed in the `issue372` branch but this was never merged. While we're here, the line needs a second correction – passing the policy argument in the second call to `lgamma`.

**Comment by jzmaddock** [comment]
My bad, as the PR wasn't on my radar I thought I'd merged it already, but apparently I'd never made it a PR in the first place :(  Done now.
