### ISSUE TITLE
pow is not in the documentation index

### ISSUE THREAD

**Issue by jzmaddock** [boostorg/math#393]
Title says it all, not sure why not yet :(

**Comment by jzmaddock** [comment]
Ah my bad, we deliberately excluded all the std lib names otherwise they're everywhere.  I'll see if I can add a manual entry.

**Comment by Shehab225** [comment]
Hey @jzmaddock ,
are you willing to accept new contributors? I am interested into contributing to this repository so, if you could explain a bit more this feature request, it would be great.
Thanks

**Comment by Rashika101** [comment]
Hey!!
I am interested into contributing to this repository. So please help me out and explain about this feature .
Thanks

**Comment by jzmaddock** [comment]
@Rashika101 @Shehab225 

Yes, we're always interested in new contributions, unfortunately for you all the easy issues tend to get dealt with pretty rapidly, and the more intractable ones get left (like this one).

So.... I would suggest you familiarise yourself with the library, and then look through the issues plus the TODO list in the docs (which I admit is terribly out of date), and just dive in by submitting PR's for things you think you can fix and/or improve.

To be honest, if we have to explain what an issue is about and how to fix it, then we could have fixed it ourselves already!

HTH, John Maddock.

**Comment by Rashika101** [comment]
@jzmaddock 
I want to work on this issue. Please assign it to me.
Thanks

**Comment by NAThompson** [comment]
@Rashika101 : There is a [feature wishlist](https://github.com/boostorg/math/issues/303).

I think doing 2D Akima splines is probably the easiest of them; although 2D Padua point quadrature is also fairly straightforward.

**Comment by Rashika101** [comment]
@NAThompson 
Will you help me??Please...

**Comment by NAThompson** [comment]
@Rashika101 : Here's some references to get you going:

Akima, H. (1978). A Method of Bivariate Interpolation and Smooth Surface Fitting for Irregularly Distributed Data Points. ACM Transactions on Mathematical Software 4, 148-164.

Akima, H. (1996). Algorithm 761: scattered-data surface fitting that has the accuracy of a cubic polynomial. ACM Transactions on Mathematical Software 22, 362–371.

R. J. Renka (1996). Algorithm 751: TRIPACK: a constrained two-dimensional Delaunay triangulation package. ACM Transactions on Mathematical Software. 22, 1-8.

**Comment by Rashika101** [comment]
@NAThompson 
Hey!!Will you please explain a little more in steps?
So that i can work...I am in a confusion loop...
Thanks
