### ISSUE TITLE
Legendre Polynomial Issue with l=0, m=-1

### ISSUE THREAD

**Issue by abhinavsns** [boostorg/math#453]
```
#include <boost/math/special_functions/legendre.hpp>

int main () {
  boost::math::legendre_p(0,-1,1.0);
  return 0;
}
```

Results in:
libc++abi.dylib: terminating with uncaught exception of type boost::wrapexcept<std::domain_error>: Error in function boost::math::tgamma_ratio<long double>(long double, long double): Gamma function ratios only implemented for positive arguments (got a=0).
Abort trap: 6

**Comment by jzmaddock** [comment]
Confirmed, we need a special case for `m = l - 1`.  Will fix shortly.
