### ISSUE TITLE
Missing include in bivariate_statistics.hpp

### ISSUE THREAD

**Issue by dgoulet** [boostorg/math#461]
Greetings,

I just updated to 1.74 and one of my project is getting this warning:

```
/usr/include/boost/math/statistics/bivariate_statistics.hpp:85:24: error: ‘sqrt’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   85 |     Real rho = cov/sqrt(Qu*Qv);
```

It appears the header is simply missing `#include <cmath>` which fixes it for me. Let me know if you would like a PR for this. I figured something that trivial is likely something you can push quickly.

Cheers!

**Comment by jzmaddock** [comment]
Sort of, it's missing a using std::sqrt as well.... otherwise it will call `::sqrt(double)` which may lose precision (long double, __float128 etc).

@NAThompson do we have a #include test for this, plus a concept check?

**Comment by NAThompson** [comment]
@jzmaddock : We do not; my bad!

**Comment by mborland** [comment]
I believe this was resolved in PR #480.

**Comment by NAThompson** [comment]
@dgoulet : Is this resolved on your end?

**Comment by NAThompson** [comment]
Assuming resolved; feel free to reopen if not.
