### ISSUE TITLE
Does the Boost Test Suite Support Clang Compilation with libc++?

### ISSUE THREAD

**Issue by linjx123456** [boostorg/math#472]
| ../boost/math/special_functions/gamma.hpp:655:27: error: call to 'log' is ambiguous
|                         + log(boost::math::constants::pi<T>())
|                           ^~~
XXX/recipe-sysroot/usr/include/bits/mathcalls.h:104:17: note: candidate function
| __MATHCALL_VEC (log,, (_Mdouble_ __x));
|                 ^
XXX/usr/include/c++/v1/math.h:953:46: note: candidate function
| inline _LIBCPP_INLINE_VISIBILITY float       log(float __lcpp_x) _NOEXCEPT       {return ::logf(__lcpp_x);}
|                                              ^
XXX/usr/include/c++/v1/math.h:954:46: note: candidate function
| inline _LIBCPP_INLINE_VISIBILITY long double log(long double __lcpp_x) _NOEXCEPT {return ::logl(__lcpp_x);}

**Comment by mclow** [comment]
"/usr/include/bits" is not part of libc++

**Comment by jzmaddock** [comment]
Yes but:

* I'm unable to find that line in current Boost, so I assume you're using an old version, and
* As @mclow says, the conflicting header is not part of libc++, I suspect you have a conflicted / messed up install of something somewhere.

Try compiling:

```
#include <cmath>
#include <math.h>

int main()
{
   using std::log;
   double d = 3.14;
   d = log(d);
}
```

If you see the same issue then it's a toolchain install issue, if not then I'm stumped.

**Comment by linjx123456** [comment]
#include <cmath>
#include <math.h>

int main()
{
   using std::log;
   double d = 3.14;
   d = log(d);
}
----it‘s ok

**Comment by linjx123456** [comment]
BOOST_AUTO_TEST_CASE( test_main )
{
   BOOST_MATH_CONTROL_FP;
   test_spots(0.0Q);                  -----------------The error is caused by test_spots(0.0Q); in test_factorials.cpp
   cout << "max factorial for __float128"  << boost::math::max_factorial<boost::floatmax_t>::value  << endl;
}

compiling Using the LLVM ,However, the GCC compilation is normal.
Another issue is test_spots (0.0Q); supported? test_spots (0.0F); is ok

**Comment by linjx123456** [comment]
> Yes but:
> 
> * I'm unable to find that line in current Boost, so I assume you're using an old version, and
> * As @mclow says, the conflicting header is not part of libc++, I suspect you have a conflicted / messed up install of something somewhere.
> 
> Try compiling:
> 
> ```
> #include <cmath>
> #include <math.h>
> 
> int main()
> {
>    using std::log;
>    double d = 3.14;
>    d = log(d);
> }
> ```
> 
> If you see the same issue then it's a toolchain install issue, if not then I'm stumped.

----it‘s ok

**Comment by linjx123456** [comment]
> Yes but:
> 
> * I'm unable to find that line in current Boost, so I assume you're using an old version, and
> * As @mclow says, the conflicting header is not part of libc++, I suspect you have a conflicted / messed up install of something somewhere.
> 
> Try compiling:
> 
> ```
> #include <cmath>
> #include <math.h>
> 
> int main()
> {
>    using std::log;
>    double d = 3.14;
>    d = log(d);
> }
> ```
> 
> If you see the same issue then it's a toolchain install issue, if not then I'm stumped.

----it‘s ok

**Comment by jzmaddock** [comment]
What is it you are trying to do - there is no `test_spots(0.0Q);` line in test_factorials.cpp nor should there be.

**Comment by linjx123456** [comment]
The latest test_factorials.cpp file still contains test_spots(0.0Q).

**Comment by jzmaddock** [comment]
Ah sorry, two different files with that name, if you're looking at libs\math\test\float128\*.cpp then nothing in that folder will build with anything except GCC.
