### ISSUE TITLE
Does the test_spots (0.0Q) Support Clang Compilation with libc++?

### ISSUE THREAD

**Issue by linjx123456** [boostorg/math#475]
../boost/lexical_cast/detail/converter_lexical.hpp:243:13: error: static_assert failed due to requirement 'has_right_shift<std::__1::basic_istream<char>, __float128, boost::detail::has_right_shift_impl::dont_care>::value || boost::has_right_shift<std::__1::basic_istream<wchar_t>, __float128, boost::detail::has_right_shift_impl::dont_care>::value' "Target type is neither std::istream`able nor std::wistream`able"

BOOST_AUTO_TEST_CASE( test_main )
{
BOOST_MATH_CONTROL_FP;
test_spots(0.0Q); -----------------The error is caused by test_spots(0.0Q); in test_factorials.cpp
cout << "max factorial for __float128" << boost::math::max_factorialboost::floatmax_t::value << endl;
}

compiling Using the LLVM ,However, the GCC compilation is normal.
Another issue is test_spots (0.0Q); supported? test_spots (0.0F); is ok

**Comment by jzmaddock** [comment]
__float128 is NOT supported with clang, and so neither is that test.

I see no such line in test_factorials.cpp BTW.
