### ISSUE TITLE
Error trying to include <boost/config.hpp> in round_fwd.hpp

### ISSUE THREAD

**Issue by vinay0000** [boostorg/math#479]
https://github.com/boostorg/math/blob/b0045c1f43ce5ff0e824d34a4ef7c35c84426d3c/include/boost/math/special_functions/detail/round_fwd.hpp#L11

Looks like a bug? There is no config.hpp in the `boost/` path (https://github.com/boostorg/math/tree/develop/include/boost)

**Comment by jzmaddock** [comment]
You need a full Boost install from www.boost.org to use Boost.Math, it isn't (yet) usable standalone.
