### ISSUE TITLE
CI Failure with quadrature

### ISSUE THREAD

**Issue by mborland** [boostorg/math#511]
Several different types quadrature failures using GCC-9, CXXSTD=17, and ARCH=PPC64LE:

[tanh_sinh_quadrature](https://travis-ci.org/github/mborland/math/jobs/756971706#L956)
[exp_sinh_quadrature](https://travis-ci.org/github/mborland/math/jobs/756971706#L1121)
[test_autodiff](https://travis-ci.org/github/mborland/math/jobs/756971706#L1430)

Most of these seem to be related to __float128

**Comment by NAThompson** [comment]
Can this be closed? It seems like we've gotten past this . . .
