### ISSUE TITLE
CI Failures with long doubles in misc tests on ARM64

### ISSUE THREAD

**Issue by mborland** [boostorg/math#513]
Several long double related test failures with GCC-9 CXXSTD=17 and ARCH=ARM64

[test_constants](https://travis-ci.org/github/mborland/math/jobs/756971717#L1057)
[std::exp](https://travis-ci.org/github/mborland/math/jobs/756971717#L1236)
[cohen_acceleration](https://travis-ci.org/github/mborland/math/jobs/756971717#L1551)
[cardinal_quadratic_b_spline](https://travis-ci.org/github/mborland/math/jobs/756971717#L1603)
[whittaker_shannon](https://travis-ci.org/github/mborland/math/jobs/756971717#L1659)
[linear_regression](https://travis-ci.org/github/mborland/math/jobs/756971717#L13980)

**Comment by mborland** [comment]
[Similar errors with ARCH=S390X](https://travis-ci.org/github/mborland/math/jobs/756971724#L1598)

**Comment by NAThompson** [comment]
Did this issue get fixed?

**Comment by mborland** [comment]
I haven't tried anything on travis since the migration happened. I can close these other architecture issues because we have no real way of testing them.
