### ISSUE TITLE
daubechies scaling test throwing bad_alloc

### ISSUE THREAD

**Issue by jzmaddock** [boostorg/math#515]
See here: https://drone.cpp.al/boostorg/math/10/85/2

@NAThompson : Is there any reason not to just catch the exception and exit?  The test crunches through about 2GB of memory which may well run the VM out of memory.

I can add the obvious patch to this PR if you're happy with that.

**Comment by jzmaddock** [comment]
daubechies_wavelet_test has a similar error though this one just says "killed" :(

https://drone.cpp.al/boostorg/math/10/94/2

**Comment by NAThompson** [comment]
@jzmaddock : Thanks for taking care of this; there is no reason to not catch the bad_alloc as you say.
