### ISSUE TITLE
double exponential docs incorrect

### ISSUE THREAD

**Issue by jzmaddock** [boostorg/math#546]
Trivial issue:

the docs have the namespace as `boost::math` rather than `boost::math::quadrature`.  It would be good to mention the namespace in each integrators sub-page as well as the overview.

I've also just fallen into a trap, in that:

`my_exp_sinh.integrate(f, a)`

Does not integrate from a to infinity, but treats `a` as an epsilon tolerance.  Not sure what we can do about that though.

**Comment by NAThompson** [comment]
First issue is fixed; double_exponential.qbk was the only file with that issue.

> Does not integrate from a to infinity, but treats a as an epsilon tolerance. Not sure what we can do about that though.

IIRC the domain of `exp_sinh` is *always* [-inf, inf].

How about `if (abs(a) > 1) { std::cerr << "Did you mistake a domain for a tolerance?" }`

**Comment by jzmaddock** [comment]
Thanks Nick!

>IIRC the domain of exp_sinh is always [-inf, inf].

[0, inf]  ;)

> How about if (abs(a) > 1) { std::cerr << "Did you mistake a domain for a tolerance?" }

Make that a `domain_error` and a check on the error tolerance, and yes, that seems sensible.

BTW we seem not to have documented anywhere whether the error tolerance is absolute or relative, likewise the error returned.  L1 also need documenting, even though that one is reasonably obvious :)

**Comment by NAThompson** [comment]
I'm trying to remember why I didn't support `[a, inf]` domains for finite `a` . . .  maybe I thought the translation was too trivial to bother with?

**Comment by jzmaddock** [comment]
>I'm trying to remember why I didn't support [a, inf] domains for finite a . . . maybe I thought the translation was too trivial to bother with?

It *is* supported, but you have to supply both ends of the range, the trap I fell into, was assuming that if I only supplied one end the other would default to +inf, but then it gets mixed up with the other constructor overload so we can't do that :(

No matter.

**Comment by NAThompson** [comment]
Well I should've put more thought into the design here, but I believe this ship has sailed as it's not worth a backwards incompatible change . . .

**Comment by NAThompson** [comment]
> BTW we seem not to have documented anywhere whether the error tolerance is absolute or relative, likewise the error returned. L1 also need documenting, even though that one is reasonably obvious :)

It looks like I did it in text rather than an equation:

"The routine stops when successive estimates of the integral I1 and I0 differ by less than the tolerance multiplied by the estimated L1 norm of the function."

This is a scale-invariant tolerance, but not quite what people think when they ask for relative error.
