### ISSUE TITLE
Merge for 1.76

### ISSUE THREAD

**Issue by jzmaddock** [boostorg/math#558]
We currently have a window of 1 day (till 26th Feb) to merge breaking changes to release.  It would have to be a coordinated Math/Multiprecision merge as well.

If there are further bug fixes, there is still time for those later, likewise we need some serious release notes this time around ;)

Is everyone OK with a release?

**Comment by mborland** [comment]
I have nothing to add before release beside PR #557. That was an accidental new dependency that I wanted to remove today since I saw your post on the ML. The campaign against the rest of the dependencies can continue for 1.77.

**Comment by ckormanyos** [comment]
I finished the activities for 1.76 on
24.feb. And I do not want to change
Any of my changes unless bugs
Arise in them
