### ISSUE TITLE
Missing "boost/utility/enable_if.hpp" in In master and boost-1.75.0

### ISSUE THREAD

**Issue by achoum** [boostorg/math#560]
Hi,

In boost-1.75.0, ``boost/math/special_functions/math_fwd.hpp`` includes ``boost/utility/enable_if.hpp`` (line 31).
However, ``boost/utility/enable_if.hpp`` does not exist in the boost-1.75.0 version of ``utility``.

**Comment by achoum** [comment]
Note: This was solved in ``develop``: https://github.com/boostorg/math/commit/ecc70fe65f5e8189c9f7e38e06d7f05d18a48498

**Comment by jzmaddock** [comment]
Yes it does, it's here: https://github.com/boostorg/core/tree/develop/include/boost/utility

**Comment by achoum** [comment]
My bad. I assumed this would be in the ``utility`` repository (instead of the ``core`` one).
