### ISSUE TITLE
Guidance for GSOC 2021

### ISSUE THREAD

**Issue by ameyachawla99** [boostorg/math#584]
Respected sir/madam

Hi , I am Ameya Chawla currently pursuing my B.Tech in Computer Science and Engineering .
I read about your organization in GSOC 2021 and looking forward to work with your organization .
 I want to work on project Implement a feasible realization of FFT .

Please Guide me how should i start working 

Thank You

**Comment by ckormanyos** [comment]
Hi Ameya, I see you have properly moved this discussion to the board, where i have provided a preliminary answer to your first round of query.
