### ISSUE TITLE
Polution of global namespace with "mp"

### ISSUE THREAD

**Issue by jzmaddock** [boostorg/math#594]
@mborland : Apologies I should have spotted this before, but there are several places where `namespace mp = boost::math::tools::meta_programming;` occurs at global scope: this is a big no-no, everything should be contained with boost::math, just moving the namespace alias inside our namespaces should do the trick I hope!

I just hit this while testing a Multiprecision bug report which used `mp` as an alias for `boost::multiprecision` and clashed.

**Comment by mborland** [comment]
Locally moving it into the boost::math namespace worked fine. The were both included in the giant policy PR.

**Comment by jzmaddock** [comment]
@mborland can this be closed now, I think it's fixed?

**Comment by mborland** [comment]
This can be closed
