### ISSUE TITLE
We may need to be able to disable threading support after all.

### ISSUE THREAD

**Issue by jzmaddock** [boostorg/math#621]
Leaving aside @ckormanyos building on the metal, msvc with the /clr options does not support any of the std threading headers: `<mutex>`, `<thread>`, `<atomic>` etc.

Currently building in this mode triggers a #error in cxx03_warn.hpp which prevents **any** part of the library being used.

**Comment by ckormanyos** [comment]
> on the metal, msvc with the /clr options does not support any of the std threading headers

Oh yes, I had completely forgotten that. It was really, really a long time ago. At that time, I wanted to export some functions to Microsoft's so-called _managed C++_, using `cli_ext`headers. This is indeed a limitation.

On my huge list of things to do was to make a cursory glance at what actually needs threads, muteses and atomics. For the special functions, it seems rather limited to `tgamma`and friends. I have not seriously looked into other parts like quadrature, etc.

I would be interested if we could pursue a way to handily and reliably disable threading, for metal, python exports, CLR/.NET exports and the lot.

**Comment by mborland** [comment]
This seems to be pretty well supported at this time. Closing to cleanup our open issues.
