### ISSUE TITLE
Time to cut a release of the standalone?

### ISSUE THREAD

**Issue by NAThompson** [boostorg/math#622]
The releases workflow from github seems incredibly easy to use-I'd like to cut a standalone release after @mborland's incredibly great work on this topic.

Do we have anything we'd like to do before doing so?

**Comment by mborland** [comment]
I can't think of anything else that needs to go in. I think it would be useful to put out in the user ML and/or dev ML that a standalone beta is available. I am sure that will turn up stuff that may have been missed.

**Comment by jzmaddock** [comment]
>I can't think of anything else that needs to go in. I think it would be useful to put out in the user ML and/or dev ML that a standalone beta is available. I am sure that will turn up stuff that may have been missed.

+1

Other than that, at some point I would like to solve the build-on-msvc-clr issues and/or other platforms with no threading support.

**Comment by NAThompson** [comment]
Done!

Give it a try when you have a minute.

Also, my messages always get bounced from the mailing list, so please post  message for me.

**Comment by NAThompson** [comment]
@ax3l : You should now be able to vendorize boost.math in isolation.

**Comment by jzmaddock** [comment]
>https://github.com/boostorg/math/releases/tag/v1.76-standalone-beta

Done, let me know what email address is getting bounced and I'll investigate.

**Comment by mborland** [comment]
> Other than that, at some point I would like to solve the build-on-msvc-clr issues and/or other platforms with no threading support.

I can go through my tree and find places I dropped paths based on having threads of not. Replicating `BOOST_HAS_THREADS`  for standalone mode should not be overly difficult. Adding support for metal platforms may be a different story.

**Comment by NAThompson** [comment]
Release is cut, closing.
