### ISSUE TITLE
hypergeometric kurtosis differs from Wolfram and scipy and Wikipedia

### ISSUE THREAD

**Issue by pabristow** [boostorg/math#639]
I have reported in response to a complaint 

https://github.com/scipy/scipy/pull/14153#issuecomment-853942708

@jzmaddock Should I prepare a PR to correct this? and provide a new test?

It could just be the patch in the link above, or some update/enhancement to the docs might be better?

(I won't be able to work on this until 15 Jun).

**Comment by mckib2** [comment]
Appears to be a duplicate of #637, linking to this one
