### ISSUE TITLE
Preparing for 1.77

### ISSUE THREAD

**Issue by jzmaddock** [boostorg/math#647]
I see the next release cycle has come around again, any reason not to merge for 1.77, anything we need to do?

@NAThompson , @pabristow , @mborland  ?

**Comment by mborland** [comment]
The only bug fix I have that should make it is https://github.com/boostorg/math/pull/648.

**Comment by NAThompson** [comment]
Looks like #646 will also be necessary.

**Comment by ckormanyos** [comment]
I did not make as much progress as hoped on `<cstdfloat.hpp>` in #506. It's too late for significant progress now. So I'll need to push that off till 1.78.

**Comment by pabristow** [comment]
We definitely should merge PR to correct the error in hypergeometric distribution kurtosis. Hypergeomkurtosis #642.  I was sort or waiting for a review, but will do it today.
