### ISSUE TITLE
Should we add color tables?

### ISSUE THREAD

**Issue by NAThompson** [boostorg/math#649]
After adding the bilinear interpolator I realized a good QC would be to make an png image using it, via a scientific color table.

I've already written a color table code [here](https://github.com/NAThompson/DifferentiableRaytracing/blob/master/include/drt/color_maps.hpp); would it be a good match for this library?

**Comment by mborland** [comment]
I would vote that it would be useful to have in tools; there is already other plotting functionality in there. The end user would then have a documented tool internal to the library instead of having to roll their own solution from something like matplot++.

**Comment by jzmaddock** [comment]
+1.

What are you using to write the output file - Boost.GIL, or something else?

**Comment by NAThompson** [comment]
I've used lodepng to write the files; see [here](https://github.com/NAThompson/DifferentiableRaytracing/blob/42b999e62276eb7b42cbbf14977c46fdf5b3e675/include/drt/png.hpp). I think Boost.GIL would also be a good choice for example code.
