### ISSUE TITLE
Update boost math

### ISSUE THREAD

**Issue by pascalpfeil** [boostorg/math#708]
Could you update boost math please?

When using the latest boost release with cmake `ExternalProject_Add`, https://github.com/boostorg/math/issues/675 makes my project not compile.

**Comment by pascalpfeil** [comment]
Any news? The fix would be simply updating the boost math submodule to `v1.77-standalone` in https://github.com/boostorg/boost

**Comment by NAThompson** [comment]
@pascalpfeil : Will the 1.78 release work for you?

**Comment by pascalpfeil** [comment]
I think so

**Comment by pascalpfeil** [comment]
No worries, I am as well :)

**Comment by pascalpfeil** [comment]
Basically, when I use boost as a dependency and then compile my project I get
```
/usr/include/boost/math/common_factor_ct.hpp:17:68: error: _Pragma takes a parenthesized string literal
   17 | BOOST_MATH_HEADER_DEPRECATED("<boost/integer/common_factor_ct.hpp>");
      |                                                                    ^
In file included from /usr/include/boost/math/common_factor_ct.hpp:15,
                 from test.cpp:1:
/usr/include/boost/math/common_factor_ct.hpp:17:1: error: ‘_Pragma’ does not name a type
   17 | BOOST_MATH_HEADER_DEPRECATED("<boost/integer/common_factor_ct.hpp>");
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ```

This is already fixed in boost math standalone, but as the main boost repo's submodule is still in a old state, I still get these errors when using boost unmodified.

**Comment by pascalpfeil** [comment]
Actually, this commit did fix it: https://github.com/boostorg/boost/commit/14664740f577a2c2855e8996efbc05c031cdf8b9
