### ISSUE TITLE
Ready for 1.78?

### ISSUE THREAD

**Issue by jzmaddock** [boostorg/math#715]
Are there any show stoppers preventing a merge to master?

@NAThompson hows the cubic_roots_test now?

**Comment by jzmaddock** [comment]
@NAThompson Ugh, always something: https://app.circleci.com/pipelines/github/boostorg/math/367/workflows/04c05dec-dbab-4cd3-af03-7355553cf84d/jobs/365

**Comment by NAThompson** [comment]
@jzmaddock : Yup, my bad, will fix.

**Comment by NAThompson** [comment]
BTW why do we care if there's non-ASCII characters in comments? If appears that every compiler handles it just fine.

**Comment by jzmaddock** [comment]
>BTW why do we care if there's non-ASCII characters in comments? If appears that every compiler handles it just fine.

Sorry no idea what the rationale was.  I do know that users with far-eastern character sets can sometimes have all kinds of issues with non-ASCII characters, but I don't know the details....

**Comment by jzmaddock** [comment]
OK, since we're up against the beta deadline (tomorrow!), I've done a merge to master, if we can fix the remaining CI failures in beta though that would be great.

**Comment by NAThompson** [comment]
@jzmaddock : Could you merge #716?

**Comment by jzmaddock** [comment]
> Could you merge #716 for the beta?

Yep, I'll let the CI play out a little longer first... we have a few hours yet and it's nearly run through...

**Comment by jzmaddock** [comment]
Can everyone please check that https://github.com/boostorg/math/commit/e000cf5dd1a9e02c322f5b094a8c057c6683b60c#diff-f4da1e74afb45ab98ca3a2ad30842e21a37b13a5956514b904889f941100f83e covers the release notes for this release?

**Comment by NAThompson** [comment]
@jzmaddock : Is there a spurious `std::cout` in `tanh_sinh_detail` in that commit?

**Comment by jzmaddock** [comment]
>  Is there a spurious std::cout in tanh_sinh_detail in that commit?

Aaah, reverted.

**Comment by ckormanyos** [comment]
> covers the release notes for this release?

Hi @jzmaddock 

It's super trivial, but #507 has (think this is post-1.77):
- Improve certain edge cases for `<cstdfloat>` complex-valued elementary functions.

Cc: @mborland and @NAThompson

**Comment by NAThompson** [comment]
Just read the docs for the cubic roots and for the Bezier polynomials, where are our new features for this release; they look good.

Note that these updates are only on develop, not yet on master; is that expected?

**Comment by jzmaddock** [comment]
>Note that these updates are only on develop, not yet on master; is that expected?

The docs?  I've only just added them and master is currently closed for the Beta, once it re-opens we can merge the doc changes, plus whatever we need to get our CI clean again.

**Comment by jzmaddock** [comment]
Hopefully this will green up CI: https://github.com/boostorg/math/commit/40605d0b78c397ceb337d1c427aa3e1d2a4803f6

**Comment by jzmaddock** [comment]
Docs and history are merged, CI is green, closing down.
