### ISSUE TITLE
exp_sinh.hpp uses old-style casts

### ISSUE THREAD

**Issue by rnburn** [boostorg/math#740]
boost quadrature errors with the message below when compiled with the flags `-Werror,-Wold-style-cast`

It's easy enough to work around but there shouldn't be any need to use old-style casts.

```
external/boost/boost/math/quadrature/exp_sinh.hpp:64:18: error: use of old-style cast [-Werror,-Wold-style-cast]
        if (a == (Real) 0)
                 ^      ~
```

**Comment by NAThompson** [comment]
Yup, I'll fix it.

**Comment by rnburn** [comment]
Thanks! 

Btw looking through the code, I see a few other places where it's doing old-style casts:
https://github.com/boostorg/math/blob/develop/include/boost/math/quadrature/detail/exp_sinh_detail.hpp#L225

**Comment by NAThompson** [comment]
I'll fix 'em all!

**Comment by NAThompson** [comment]
@rnburn : Should be fixed in 741. Once the CI cycles I'll merge; are you consuming the standalone? If so you can consume this independently of the rest of boost.

**Comment by rnburn** [comment]
Great! Thanks for the the quick turnaround.

I was using it through https://github.com/nelhage/rules_boost, but I'm sure I'll be able to find a way to adopt the fix.

**Comment by NAThompson** [comment]
@rnburn : Fix is merged.

Leaving this issue open as I made the same mistake in sinh-sinh and tanh-sinh quadrature, so I'll close once I get those done.

**Comment by NAThompson** [comment]
@jzmaddock : Will I get you into merge hell if I make those diffs? I see you have a pretty large outstanding diff to these files.

**Comment by jzmaddock** [comment]
I've just merged one lot of develop changes, if you don't mind holding off until CI has cycled on https://github.com/boostorg/math/pull/722 I'll merge all that to develop if it's clean now.  If not clean, just go ahead and I'll merge and resolve the conflicts on the branch, the merge conflicts aren't that awful.

**Comment by NAThompson** [comment]
Just opened a PR which completely removes all old-style casts in all the double-exponential quadratures. Closing . . .
