### ISSUE TITLE
boost::math::tools::cubic_roots sometimes returns incorrect roots (2)

### ISSUE THREAD

**Issue by SATovstun** [boostorg/math#757]
Minimal working example:
```
#include <iostream>
#include <boost/math/tools/cubic_roots.hpp>

int main()
{
	using boost::math::tools::cubic_roots;
	
	std::cout << "((x+1)^2+1)*(x+1) = x^3 + 3*x^2 + 4*x + 2 = 0:\n";
	std::cout << "True root: -1\n";
	auto roots1 = cubic_roots<double>(1, 3, 4, 2);
	std::cout << "Boost roots: " << roots1[0] << ", " << roots1[1] << ", " << roots1[2] << "\n\n";
	
	std::cout << "x^3 + 10000*x^2 + 200*x + 1 = 0:\n";
	std::cout << "True roots (rounded): -9999.98, -0.01001, -0.00999\n";
	auto roots2 = cubic_roots<double>(1, 10000, 200, 1);
	std::cout << "Boost roots: " << roots2[0] << ", " << roots2[1] << ", " << roots2[2] << "\n";
	
	return 0;
}
```
Output:
```
((x+1)^2+1)*(x+1) = x^3 + 3*x^2 + 4*x + 2 = 0:
True root: -1
Boost roots: -1, -1, -1

x^3 + 10000*x^2 + 200*x + 1 = 0:
True roots (rounded): -9999.98, -0.01001, -0.00999
Boost roots: -9999.98, -3413.62, -3413.62
```

**Comment by NAThompson** [comment]
Will investigate.

**Comment by fredbr** [comment]
Did some digging of my own. This issue seems to be related to numerical precision. When running the second example the branch that checks if there are 3 different roots evaluates to false.

    Real p = b/a;
    Real q = c/a;
    Real r = d/a;
    Real Q = (p*p - 3*q)/9;
    Real R = (2*p*p*p - 9*p*q + 27*r)/54;
    if (R*R < Q*Q*Q) {
        Real rtQ = sqrt(Q);

The code evaluates `R*R == Q*Q*Q` as true, because of precision errors, when in reality `R:R < Q:Q:Q` (a:b denoting the infinite precision multiplication of a and b).

**Comment by fredbr** [comment]
The code suggests implementing this paper, _Algorithm 954: An Accurate and Efficient Cubic and Quartic Equation Solver for Physical Applications_.

Maybe that implementation fixes it?

**Comment by SATovstun** [comment]
Yes, Algorithm 954 is indeed very accurate.

**Comment by NAThompson** [comment]
It's actually a bug in the root polishing. Should have a fix relatively soon.

**Comment by NAThompson** [comment]
Ok, put a partial fix in #759. I have also added a `cubic_root_condition_number` function as all these counterexamples are of the form roots = {huge_root, small_root+eps, small_root-eps}. The condition number basically explains the error, as the new unit tests exhibit that the inequality:

|exact_root - computed_root|/|exact_root| <= fudge_factor*eps*condition_number

The `fudge_factor` is currently 10, and hence this defines how much better the routine could realistically get.

Leaving open and the multiple root problem is still unexplained.

**Comment by SATovstun** [comment]
The easiest way to fix the bug with the equation `x^3 + 3*x^2 + 4*x + 2 = 0` is to replace the line
`Real A = -boost::math::sign(R)*cbrt(abs(R) + sqrt(arg));`
with the line
`Real A = (R>=0?-1:1)*cbrt(abs(R) + sqrt(arg));`

**Comment by NAThompson** [comment]
@SATovstun : Your expression gives the correct behavior in the limit R->0 of NR equation 5.6.13; thanks!

Will diff it in shortly.
