### ISSUE TITLE
powm1(0.0, -2.0) doesn't throw an exception.  Should it?

### ISSUE THREAD

**Issue by WarrenWeckesser** [boostorg/math#781]
Here's a test program that I compiled with the `develop` branch:

```
#include <iostream>
#include <boost/math/special_functions/powm1.hpp>

using namespace std;
using boost::math::powm1;


int main()
{
    try {
        double p = powm1(0.0, -2.0);
        cout << "p = " << p << endl;
    } catch (const exception& e) {
        cerr << "*** Caught: " << e.what() << endl;
        cerr << "*** Type: " << typeid(e).name() << endl;
    }
}
```
I expected `powm1(0.0, -2.0)` to throw an exception, but it does not; the program outputs `p = inf`.  Should it throw an exception?

**Comment by mborland** [comment]
I think the behavior is correct. If you compare to the error handling of [`std::pow`](https://en.cppreference.com/w/cpp/numeric/math/pow) returning infinity is expected.

**Comment by WarrenWeckesser** [comment]
OK, I'm still figuring out the conventions followed by the functions in Boost/Math/Special Functions.  Based on the [policy docs](https://www.boost.org/doc/libs/1_79_0/libs/math/doc/html/math_toolkit/pol_tutorial/policy_tut_defaults.html), I thought the default behavior would be to throw a `std::domain_error`.

I see that `log1p(-1.0)` and `atanh(±1.0)` also do not throw, so I guess this is not unusual.

On the other hand, `erf_inv(±1.0)` and `cyl_neumann(0, 0.0)` each throw an overflow error.  (Shouldn't those exceptions be *domain errors*, as the closest thing to a *pole error*?)  So in general, is the rule *"It depends, you just have to try it"*?

**Comment by NAThompson** [comment]
@WarrenWeckesser : Lol, I like that rule. Personally I find it preferable to use all the semantic space that IEEE floats gives us and like the `inf`, but I think that you could definitely argue for a domain_error.

**Comment by jzmaddock** [comment]
It's a bug, but I'm not sure in which direction: wolframalpha reports 0^-2 as complex-infinity which would be a domain error, but if we treat it as 1/0^2 then it should be a straight overflow error.
