### ISSUE TITLE
Minimum Language Standard

### ISSUE THREAD

**Issue by mborland** [boostorg/math#787]
Based on recent discussion in the ML started by @jzmaddock are we in favor of increasing the minimum language standard of Math? I would be in favor of at least 14 or 17. From the [GCC Page](https://gcc.gnu.org/projects/cxx-status.html#cxx11) g++5 (the oldest we currently test on) has complete C++-14 support. For complete C++-17 support we would move to g++7. Second order effect would be reducing our CI battery which now takes over 6 hours to run on GHA.

Thoughts @NAThompson and @ckormanyos

**Comment by NAThompson** [comment]
I'm pro-14; primarily due to the `[deprecated]` tag. It's *so* hard to evolve the library without it.

**Comment by ckormanyos** [comment]
> in favor of increasing the minimum language standard of Math

Although I encouraged retention of 11, I've got no issue whatsoever if the consensus is to jump to 14 or higher.

> g++5 (the oldest we currently test on) has complete C++-14

There will probalby be some inconsistencies in GCC5's implementation of C++14. That compiler was coming of age around 2013 so the specification was really new at that time. If GCC5 proves to be problematic, one compromise might be reducing its support to a subset of core functions such as most of spec-func.

> Second order effect would be reducing our CI battery which now takes over 6 hours to run on GHA...

And we keep adding even more compilers in the advent of Jammy, etc.

It's not my decision, but here are some ideas I've used on other projects.
- Consider reducing the sope of CI on GCC5.
- Some of the compilations might be redundant. I've found, for instance, that folks tend to stick to the _endpoints_ so on GCC 11 and clang 12, for instance, maybe just run in CI `-std=c++11` and `-std=c++20`.
- There might be similar endpoint-like redundancies around the entire lineage of compilers.

**Comment by mborland** [comment]
> There will probalby be some inconsistencies in GCC5's implementation of C++14. That compiler was coming of age around 2013 so the specification was really new at that time. If GCC5 proves to be problematic, one compromise might be reducing its support to a subset of core functions such as most of spec-func.
> 

I've linked a PR giving C++14 a try with GCC5 so we'll see how that goes.

**Comment by ckormanyos** [comment]
>> probalby be some inconsistencies in GCC5's implementation of C++14

> I've linked a PR giving C++14 a try with GCC5 so we'll see how that goes

Great idea! Thank you Matt

**Comment by NAThompson** [comment]
However, remember the primary purpose of setting the minimum language standard to C++14 is to not have to deal with inconsistent C++11.

Also, the only thing I use out of C++14 is the `[[deprecated]]` tag; if the compiler doesn't get that I think we should say 'don't support'.

**Comment by mborland** [comment]
The CI run for the linked PR is clean so we would have no issues moving to C++14 even with GCC-5 testing.

**Comment by ckormanyos** [comment]
>> I would be in favor of at least 14

The call for 14 seems to be loud and clear in this thread and elsewhere.

>  we will need to give notice of the change and deprecate C++11 support for about 3 release prior to the change

If/when we do this, I think we should synchronize the exact same change(s) in Multiprecision, as these libs are intimately linked with each other.

- Why wait?
- Is there a consensus already?
- Or is this too quick?
- Add mention in the docs for both Math and Multiprecision in the July trimester for 1.80, to be switched in summer 2023?

Thoughts?

@jzmaddock and @NAThompson and @mborland

**Comment by ckormanyos** [comment]
> If we want to hit, say, summer 2023, should we add mention in the docs

... like similar to this?

## ⚠️  Deprecation of C++11
**Expected as of July 1, 2023, Boost.Math raises minimum standard to C++14 (and C++11 will no longer be supported)**

**Comment by mborland** [comment]
> > If we want to hit, say, summer 2023, should we add mention in the docs
> 
> ... like similar to this? I must admit, it looked pretty harsh upon seeing it.
> 
> ## ⚠️ Deprecation of C++11
> **Expected as of July 1, 2023, Boost.Math raises minimum standard to C++14 (and C++11 will no longer be supported)**

I think that works. I can edit the attached PR to add C++14 testing to GCC-5 so we know that we are not going to break anything in the meantime.

**Comment by NAThompson** [comment]
I guess the way to do this is to also put a `#warning` that gets emitted in C++11 mode, as I expect few people will read the README and fewer still will remember.

**Comment by ckormanyos** [comment]
See also https://github.com/boostorg/multiprecision/issues/467
