### ISSUE TITLE
A documentation bug reported for Akima Interpolation

### ISSUE THREAD

**Issue by JonKalb** [boostorg/math#803]
owners@boost.org received this from physikqy <zhoujack14@outlook.com>

> Just report a tiny grammer mistake in the example:
> it should be:
> 
> auto spline = makima<vector(double)>(std::move(x), std::move(y));
> 
> just miss <vector(double)>
> I know this is easy to fix, but for beginners it could be more crystal.
> 
> https://www.boost.org/doc/libs/master/libs/math/doc/html/math_toolkit/makima.html
> 
> Best wishes,
> Qingyuan.
>

**Comment by jzmaddock** [comment]
@NAThompson ?

**Comment by NAThompson** [comment]
Nah, it should type-deduce right?
