### ISSUE TITLE
Drone erroring with starlark: maximum file size exceeded

### ISSUE THREAD

**Issue by mborland** [boostorg/math#849]
[This started two days ago](https://drone.cpp.al/boostorg/math) without any significant changes to the drone script (https://github.com/boostorg/math/commit/aa242e5639b61e95d10f53974a0d4285e800249e fixed a spelling error). @sdarwin do you see anything out of the ordinary?

**Comment by sdarwin** [comment]
Thanks for reporting the issue. There was a change, about two days ago on the drone server side, which would explain how the starlark file became larger, and then result in "starlark: maximum file size exceeded".  Reverting that, on the server.
