### ISSUE TITLE
Potentially return type mismatch in tanh_sinh::integrate

### ISSUE THREAD

**Issue by matwey** [boostorg/math#902]
Hello,

`tanh_sinh::integrate()` has return type of `decltype() const`, where `decltype()` is usually some floating point type returned by value. 

https://github.com/boostorg/math/blob/81b7477cefdf879121f5c1ae8c60276bccd0569f/include/boost/math/quadrature/tanh_sinh.hpp#L47

This has no much sense comparing to return just `decltype()`. Didn't you mean other function signature instead?
```
const -> decltype()
```

Making the function itself to be const instead?

**Comment by matwey** [comment]
No, it doesn't.

https://en.cppreference.com/w/cpp/language/function

const qualification is placed before `->`. Everything placed after `->` is trailing return type.


Also, please look at the following example:

https://wandbox.org/permlink/wVPM3IeWfwJTIFBt

```
#include <boost/math/quadrature/tanh_sinh.hpp>

using boost::math::quadrature::tanh_sinh;

class my_x {
public:
    float get_value() const {
        return integrator_.integrate([]() {
            return 1.0f;
        });
    }
private:
    tanh_sinh<float> integrator_;
};

int main() {
    
    return 0;
}
```

It fails to compile because `tanh_sinh<float>::integrate()` is NOT cons-qualified function.

**Comment by jzmaddock** [comment]
The OP is correct, and there are a few of these.... I'll post a PR shortly.
