### ISSUE TITLE
Complex number functions

### ISSUE THREAD

**Issue by evanmiller** [boostorg/math#911]
Are these still needed?

https://www.boost.org/doc/libs/1_81_0/libs/math/doc/html/inverse_complex.html

I see that all six of these functions are in [std::complex](https://en.cppreference.com/w/cpp/numeric/complex) as of C++11.

**Comment by mborland** [comment]
Since we are moving to C++14 in the next release we could add the `[[deprecated("Replaced by C++11")]]` attribute to these.

**Comment by jzmaddock** [comment]
I'm cool with that.

**Comment by NAThompson** [comment]
Are we sure that 1) these don't work with multiprecision, and 2) they aren't used by some standard library implementation?

**Comment by mborland** [comment]
> Are we sure that 1) these don't work with multiprecision, and 2) they aren't used by some standard library implementation?

1) They return std::complex<T> which is limited to `float`, `double`, and `long double`

2) That would be a question for @CaseyCarter or @StephanTLavavej. Does MSVC use Boost.Math for complex special functions? I know you use some of the others.

**Comment by ckormanyos** [comment]
> work with multiprecision

When I was recently writing my new `cpp_double_fp_backend` for Multiprecision, I got the impression that these functions were used in some of the tests. I'm not sure if they are actually needed for the Multiprecision-backend implementations, but i'll try to take a look, since i was recently just snoping around these areas.

**Comment by StephanTLavavej** [comment]
We don't use Boost.Math for `<complex>`'s inverse trig functions; our use is restricted to `[sf.cmath]`.

**Comment by ckormanyos** [comment]
> We don't use Boost.Math for `<complex>`'s inverse trig functions; our use is restricted to `[sf.cmath]`.

Cool

**Comment by ckormanyos** [comment]
> Are we sure that 1) these don't work with multiprecision

No, personally I'm really unsure of that. Just about every floating-point backend [includes the headers](https://github.com/boostorg/multiprecision/blob/8de45037b62b3405139d73d7a14acf0831bf63b6/include/boost/multiprecision/cpp_bin_float.hpp#L30) when Boost.Math is available. If this is absolutely necessary, I'm not sure.

**Comment by jzmaddock** [comment]
No std::complex can not be used for multiprecision types.  But... the scalar versions for float/double/long double could well be deprecated I guess.  Does that make things worse/less generic though?
