### ISSUE TITLE
Typo in students T example code

### ISSUE THREAD

**Issue by JohnBarrabas** [boostorg/math#957]
Boost 1.71.0

In the file https://www.boost.org/doc/libs/1_43_0/libs/math/example/students_t_two_samples.cpp

`
cout << setw(55) << left << "Pooled Standard Deviation" << "=  " << v << "\n";
`

should be

`
cout << setw(55) << left << "Pooled Standard Deviation" << "=  " << sp << "\n";
`

The "v" variable is degrees of freedom, the "sp" variable is the standard deviation.

The [boost documentation page](https://www.boost.org/doc/libs/1_43_0/libs/math/doc/sf_and_dist/html/math_toolkit/dist/stat_tut/weg/st_eg/two_sample_students_t.html) describing this file also has the error embedded in the text:

`
   Pooled Standard Deviation  =  326.00000     <-- Incorrect number shown in html page describing sample code
`

**Comment by WarrenWeckesser** [comment]
You have linked to an old version (1.43.0) of the example.  That mistake was [fixed 10 years ago](https://github.com/boostorg/math/commit/1211184b202d112d8cd4dea6a322da0686184c4c).  Take a look at the latest released version (1.81.0): https://www.boost.org/doc/libs/1_81_0/libs/math/example/students_t_two_samples.cpp

**Comment by jzmaddock** [comment]
Closing as obsolete, please re-open if I've missed something.
