### ISSUE TITLE
add constants

### ISSUE THREAD

**Issue by gpeterhoff** [boostorg/math#980]
Can you please add 2 constants to boost::math::constants:
root_five = sqrt(5)
psi = 1 - phi
These are needed e.g. for the calculation of Fibonacci numbers.

thx
Gero

**Comment by mborland** [comment]
The value of [psi](https://en.wikipedia.org/wiki/Reciprocal_Fibonacci_constant) is available as `reciprocal_fibonacci`. I can add `root_five`. We also have `<boost/math/special_functions/fibonacci.hpp>` if that's what you need.

**Comment by gpeterhoff** [comment]
I meant this [psi](https://en.wikipedia.org/wiki/Fibonacci_sequence#Closed-form_expression) = -0.618033988749...
