### ISSUE TITLE
Bad link in the Weibull distribution docs

### ISSUE THREAD

**Issue by WarrenWeckesser** [boostorg/math#985]
In https://www.boost.org/doc/libs/1_82_0/libs/math/doc/html/math_toolkit/dist_ref/dists/weibull_dist.html, there is a link for the book *Extreme Value Distributions, Theory and Applications* by Samuel Kotz & Saralees Nadarajah.  The link points to `http://www.worldscibooks.com/mathematics/p191.html`, but that link now ends up at an unrelated advertisement in Japanese.

**Comment by mborland** [comment]
Confirmed; I'll point it towards a google books link.
