### ISSUE TITLE
float128 with gcc master

### ISSUE THREAD

**Issue by sloriot** [boostorg/math#992]
Hi,

with gcc@ce2188e4320cbb46d6246bd3f478ba20440c62f3, I have the following error during compilation:

```
boost_1_82_0/include/boost/math/cstdfloat/cstdfloat_limits.hpp:46:13: error: redefinition of ‘class std::numeric_limits<__float128>’
   46 |       class numeric_limits<boost::math::cstdfloat::detail::float_internal128_t>
```

I guess it has to do with `BOOST_CSTDFLOAT_HAS_INTERNAL_FLOAT128_T` being not correctly defined after gcc's update or something like that. I only tested boost 1.82 (sorry if it has already been fixed in HEAD).

cc @afabri

**Comment by sloriot** [comment]
minimal example:
```
#include <boost/math/cstdfloat/cstdfloat_limits.hpp>

int main()
{}
```

**Comment by mborland** [comment]
> minimal example:
> 
> ```
> #include <boost/math/cstdfloat/cstdfloat_limits.hpp>
> 
> int main()
> {}
> ```

I don't see it with GCC 13.1 on godbolt: https://godbolt.org/z/h39GTMz16.

**Comment by sloriot** [comment]
that's gcc master targeting gcc 14

**Comment by mborland** [comment]
> that's gcc master targeting gcc 14

That's fun. Thanks for the heads up.

**Comment by afabri** [comment]
x86-64 gcc (trunk)   in godbolt, right?

**Comment by mborland** [comment]
> x86-64 gcc (trunk) in godbolt, right?

Yes, and it does reproduce the error.
